name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: actions/setup-gh@v2

      - name: Check GH_TOKEN
        run: echo "GH_TOKEN is set"

      - name: Check PR author
        id: check_author
        run: echo "is_dependabot=$([[ '${{ github.actor }}' == 'dependabot[bot]' ]] && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Check if PR is mergeable
        id: check_mergeable
        run: |
          pr_number=${{ github.event.pull_request.number }}
          pr_info=$(gh pr view $pr_number --json mergeable)
          echo "mergeable=$(jq -r .mergeable <<< "$pr_info")" >> $GITHUB_ENV

      - name: Auto-merge Dependabot PR
        if: env.is_dependabot == 'true' && env.mergeable == 'true'
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
