name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if the PR is from Dependabot
      - name: Check PR author
        id: check_author
        run: |
          echo "::set-output name=is_dependabot::$(if [[ '${{ github.actor }}' == 'dependabot[bot]' ]]; then echo true; else echo false; fi)"

      # Automatically merge if it is Dependabot and is mergeable
      - name: Auto-merge Dependabot PR
        if: steps.check_author.outputs.is_dependabot == 'true' && github.event.pull_request.mergeable == true
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
